spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javafx
    username: root
    password: 123456
#  shardingsphere:
#    datasource:
#      names: ds0
#      ds0:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/javafx
#        username: root
#        password: 123456
#        type: com.zaxxer.hikari.HikariDataSource
#    sharding:
#      tables:
#        tb_message:
#          actualDataNodes: ds0.tb_message_${0..31}
#          tableStrategy:
#            inline:
#              shardingColumn: user_id
#              algorithmExpression: tb_message_${user_id % 31}
#        binding_tables:
#          - tb_message
#      default_dataSource_name: ds0
#      default-table-strategy:
#        none:



