# mybatis-plus 数据库字段下换线转小驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.my.liufeng.chat.entity




spring:
  application:
    name: fx
  profiles:
    include: datasource
  data:
    couchbase:
      scope-name: singleton
netty:
  port: 10030


logging:
  level:
    root: debug
